name: Deploy to Vercel

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: Create output
        run: sh ./build.sh
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Push to Another Repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: yueunfive
          destination-repository-name: remini
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo ${{ steps.push_directory.outputs.DESTINATION_CLONED_DIRECTORY }}
